name: Update Live Core Fees JSON

on:
  workflow_dispatch:
  schedule:
    # Every hour
    - cron: "0 * * * *"

jobs:
  generate_fees_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Collect fees
      env:
        ETHNODEURL: ${{ secrets.ETHNODEURL }}
        ARBNODEURL: ${{ secrets.ARBNODEURL }}
        POLYNODEURL: ${{ secrets.POLYNODEURL }}
        BASENODEURL: ${{ secrets.BASENODEURL }}
        GNOSISNODEURL: ${{ secrets.GNOSISNODEURL }}
        GNOSIS_API_KEY: ${{ secrets.GNOSIS_API_KEY }}
        AVALANCHENODEURL: ${{ secrets.AVALANCHENODEURL }}
        POLYZKEVMNODEURL: ${{ secrets.POLYZKEVMNODEURL }}
      run: |
        pwd
        pip3 install -r requirements.txt
        python3 main.py

    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "feat: new fees report"
        title: "New Fees Report"
        branch: gha-fees-report
        delete-branch: true
        labels: "Fees-Report"
