name: Update Live Core Fees JSON

on:
  workflow_dispatch:
  schedule:
    # every 12 hours
    - cron: "0 0,12 * * *"

jobs:
  generate_fees_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "collect-fees-cron"

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Collect fees
        env:
          DRPC_KEY: ${{ secrets.DRPC_KEY }}
          GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
        run: |
          pwd
          pip3 install -r requirements.txt
          python3 main.py

      - name: Commit CSV file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: "collect-fees-cron"
          file_pattern: "fee_allocator/allocations/current_fees.csv"
          commit_message: "ci: dump csv file with all current fees"
