name: Get Latest Mimic Report

on:
  workflow_dispatch:
  schedule:
    # every thursday at 9am utc
    - cron: "0 9 * * THU"

jobs:
  generate_fees_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Collect report
        run: |
          pwd
          pip3 install -r requirements.txt
          python3 fee_allocator/fees_collected/get_report.py

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: add latest mimic report"
          title: "New Fees Report"
          branch: gha-mimic-report
          delete-branch: true
